version: '3.8'

services:

  mongodb:
    image: "mongo:${mongoversion}"
    restart: unless-stopped

  assets:
    image: "gnaudio/jabra-xpress-assets:${jabraxpressassetsversion}"
    restart: unless-stopped
    
  compliancereporter:
    image: gnaudio/jabra-xpress-cron-compliancereporter:${jabraxpresscroncompliancereporterversion}
    restart: unless-stopped

  frontend:
    image: gnaudio/jabra-xpress-frontend:${jabraxpressfrontendversion}
    environment:
    - "ENDPOINT=https://${jabraxpressbackendsubdomain}.${domain}"
    restart: unless-stopped

  backend:
    image: gnaudio/jabra-xpress-api:${jabraxpressapiversion}
    environment:
    - "ConnectionStrings:XpressDatabaseSqlServer=Server=tcp:sqlserver,1433;Initial Catalog=xpress;User ID=sa;Password=mssql1Ipw;Connection Timeout=30;"
    - "ConnectionStrings:MongoDb=mongodb://mongodb/raw"
    - "DefaultAnalyticsEndpoint=https://${jabraxpressanalyticssubdomain}.${domain}/api/v1/Analytics"
    - "JDODownload=https://${jabraxpressassetssubdomain}.${domain}/"
    - "NetworkEndpoint=https://${jabraxpressbackendsubdomain}.${domain}"
    - "SDK:fwURL_base=https://${jabraxpressbackendsubdomain}.${domain}"
    - "SDK:fsURL_base=https://${jabraxpressbackendsubdomain}.${domain}"
    - "Security:PackageTokens:IssuerKey=${PackageTokens}"
    - "Security:ClientTokens:IssuerKey=${ClientTokens}"
    - "Security:TokenProtection:Key=${TokenProtection}"
    restart: always
    depends_on:
    - mongodb
    - assets
    - sdkbackend
    - sqlserver
    - nginxreversemanager

  sdkbackend:
    image: gnaudio/fds.api:${fdsapiversion}
    environment:
    - "Storage:SDKCopyUrl=https://${jabraxpressbackendsubdomain}.${domain}"
    restart: unless-stopped

  analytics:
    image: gnaudio/jabra-xpress-analytics:${jabraxpressanalyticsversion}
    environment:
    - "ConnectionStrings:MongodbServer=mongodb://mongodb/raw"
    - "Security:PackageTokens:IssuerKey=${PackageTokens}"
    - "Security:ClientTokens:IssuerKey=${ClientTokens}"
    - "Security:TokenProtection:Key=${TokenProtection}"
    depends_on:
    - mongodb
    restart: unless-stopped

  analytics-cron:
    image: gnaudio/jabra-xpress-analytics-cron:${jabraxpressanalyticscronversion}
    environment:
    - "MONGODBCONNECTIONSTRING=mongodb://mongodb/raw"
    depends_on:
    - mongodb

  sqlserver:
    image: mcr.microsoft.com/mssql/server:${mssqlserverversion}
#    ports:
#      - 1433:1433
    volumes:
      - jabraxpresssqlmssql:/var/opt/mssql
      - jabraxpresssqlsqlserver:/var/opt/sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql1Ipw
    restart: unless-stopped
      
  nginxreversemanager:
    image: 'jc21/nginx-proxy-manager:${nginxproxymanagerversion}'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - nginxreversemanagerdata:/data
      
volumes:
  jabraxpresssqlmssql:
  jabraxpresssqlsqlserver:
  nginxreversemanagerdata: